




.build/uno/src/sketch.cpp : src/sketch.ino
	@mkdir -p .build/uno/src
	@echo [93msrc/sketch.ino[0m
	@/Users/Junior/Library/Enthought/Canopy_64bit/User/bin/ino preproc  -o $@ $^


all : .build/uno/src/sketch.cpp
	@true

